### ISSUE TITLE
Redux Devtools extension error: window not defined

### ISSUE THREAD

**Issue by VinSpee** [kiki-le-singe/react-redux-universal-boilerplate#55]
Hi! I started a new project using this boilerplate and am enjoying it so far! I did, however, run in to an issue while using the [Redux DevTools Extension](http://github.com/zalmoxisus/redux-devtools-extension).

The exact error is:

```
  ReferenceError: window is not defined
      at configureStoreDev (/Users/vincentspeelman/Projects/TED/cinema/src/common/redux/store/configureStoreDev.js:14:7)
      at handleRender (/Users/vincentspeelman/Projects/TED/cinema/src/server/utils/index.js:28:17)
      at dispatch (/Users/vincentspeelman/Projects/TED/cinema/node_modules/koa-compose/index.js:43:32)
      at next (/Users/vincentspeelman/Projects/TED/cinema/node_modules/koa-compose/index.js:44:18)
      at createGenerator (/Users/vincentspeelman/Projects/TED/cinema/node_modules/koa-convert/index.js:24:16)
      at next (native)
      at Object.proxy (/Users/vincentspeelman/Projects/TED/cinema/node_modules/koa-proxy/index.js:26:23)
      at next (native)
      at onFulfilled (/Users/vincentspeelman/Projects/TED/cinema/node_modules/co/index.js:65:19)
      at /Users/vincentspeelman/Projects/TED/cinema/node_modules/co/index.js:54:5
```

I presume it's because `configureStore.dev.js` is referencing `window`:

``` js
  if (__DEBUG__) {
    finalCreateStore = compose(
      applyMiddleware(sagaMiddleware),
      window.devToolsExtension ? window.devToolsExtension() : f => f
    )(createStore);
```

Any idea how I can get this to stop erroring?

Thanks!

**Comment by kiki-le-singe** [comment]
Hi!

Thanks for your return.

Yes I think I have an idea about this error. This boilerplate allows doing Universal/Isomorphic apps, so your application can run both client-side and server-side. Window Object doesn't exist on server-side.

I think you can correct your error like that:

``` javascript
if (__DEBUG__) {
    finalCreateStore = compose(
      applyMiddleware(sagaMiddleware),
      (__CLIENT__ && window.devToolsExtension) ? window.devToolsExtension() : f => f
    )(createStore);
```

In you app it is possible to differentiate the server and client side using some [globals](https://github.com/kiki-le-singe/react-redux-universal-boilerplate#globals) variable:

``` javascript
if (__CLIENT__) {
  // only on the client
}

if (__SERVER__) {
  // only on the server
}
```

You may also be interested in the following lifecycle methods: [componentDidMount](https://facebook.github.io/react/docs/component-specs.html#mounting-componentdidmount)

> "only on the client (not on the server)"

So if you use some libraries that depend on window in your components, you should use them in componentDidMount.

**Comment by VinSpee** [comment]
Thanks! That should certainly solve it. I will try it when I get home. Thank you again.

**Comment by VinSpee** [comment]
this resolved my issue. Thanks so much!
